# Generated by Django 3.0.6 on 2020-05-13 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200513_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 20, 22, 49, 488055), verbose_name='date published'),
        ),
    ]
