# Generated by Django 3.0.6 on 2020-05-13 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200513_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 21, 4, 29, 51697), verbose_name='date published'),
        ),
    ]
